### ISSUE TITLE
razorserver fact is causing facter command to hang on non-razor servers

### ISSUE THREAD

**Issue by kd8ion** [Lavaburn/puppet-razor#15]
The razorserver fact is throwing an error when executed on a non-razor server.  The logic is intended to find a port listening on 8150 or 8080.  Other applications can and will use these ports for their own use.  If there is a port open on either 8150 or 8080, then it tries to communicate to the razor API to determine razorserver version.  On a non-razor server, this is causing the fact to hang or throw an error because /usr/local/bin/razor will not exist.  Suggest adding a file exists check for /usr/local/bin/razor before checking if the port is open.  This should reduce the errors on non-razor servers.

**Comment by Lavaburn** [comment]
Fixed.
