### ISSUE TITLE
microkernel archive not getting installed

### ISSUE THREAD

**Issue by n2ygk** [Lavaburn/puppet-razor#7]
With compile_microkernel == false, the microkernel appears to get downloaded from the appropriate microkernel_url (defaults to http://links.puppetlabs.com/razor-microkernel-latest.tar) but "disappears" somewhere. It does not show up in /var/lib/razor/repo-store/. Here's the puppet run output:

```
==> razor: Notice: /Stage[main]/Razor::Microkernel/Archive[razor-microkernel]/Archive::Download[razor-microkernel.tar]/Exec[download archive razor-microkernel.tar and check sum]/returns: executed successfully
```

This is using your Lavaburn/puppet-archive fork of gini-archive per your README instructions. Here's how I install it (via Vagrant bootstrap script):

```
git clone https://github.com/Lavaburn/puppet-archive.git
puppet module build puppet-archive
sudo puppet module install puppet-archive/pkg/*.tar.gz
```

BTW, thanks for developing this puppet module given the lack of progress by Puppet Labs. This is the last little nit and then I'm able to build a fully functional razor server in a box that I use to provision physical servers that lack Internet access (via crossover cable).

**Comment by Lavaburn** [comment]
That is strange. Do you have the complete output? What Exec's are run next (without disabling checksum as per the change to archive module,  the module would remove the file due to invalid checksum file)?

All the changes to gini/archive have been pushed upstream, so there should be no need to use my version anymore.

**Comment by n2ygk** [comment]
It's possible it's just timing out. I'm running this on a virtual box on a
5 year old MacBook Pro. I'll see if I can reproduce. Thanks.
/a

**Comment by n2ygk** [comment]
It turns out I was not port-forwarding the razor server port from the guest to the host and this particular step was using the host IP instead of localhost. Once I set port forwarding in the Vagrantfile, this is working fine!

BTW, the entire environment is updated to latest virtualbox 5.1.6 r110634, vagrant 1.8.6, centos 7.2 CentOS-7-x86_64-DVD-1511 (with boxcutter/centos efb623d), puppet-3.8.7-1.el7.noarch, razor-server-1.3.0-1.el7.noarch, OS X 10.11.6 on newer Macbook Pro, etc. (I'm afraid to upgrade to Sierra to see what breaks;-)

Sorry for the long delay in responding. Nothing like a crashed server to motivate me:-)
